import { capitalize } from "@/utils/stringExtensions";
import { COMMON_TEXTS } from "../shared/(texts)/app-texts";
import "@/utils/stringExtensions";

export const DASHBOARD_TEXTS = {
  AI_COACH_CARD: {
    Z_ACTIVITY: "Будь ласка, опишіть вашу активність для аналізу.",
    Z_CALORIES: "Будь ласка, вкажіть спалені калорії.",
    Z_SELECT_WORKOUT: "Будь ласка, виберіть тренування.",
    TRANING: "тренування",
    UNIT_CALORIES: COMMON_TEXTS.UNIT_KILOCALORIE,
    MANUAL_ENTER: "Ручний запис",
    TOAST_ERROR: "Вибране тренування не знайдено.",
    TOAST_SUCCESS: "Активність успішно додано!",
    DELETE_ACTIVITY: "Ви впевнені, що хочете видалити цю активність?",
    DELETED: "Активність видалено!",
    CONFIRM_DELETE: COMMON_TEXTS.CONFIRM_DELETE,
    CANCEL: COMMON_TEXTS.CANCEL,
    TODAY_ACTIVITY: "Сьогоднішня активність",
    ALL_ACTIVITY: "Відстеження активності",
    AI_ANALISIS: "ШІ Аналіз",
    MY_ENTER: "Мій запис",
    AI_PLACEHOLDER: "Легкі садові роботи протягом 60 хвилин.",
    MANUAL_PLACEHOLDER: "Спалені калорії",
    SELECT_WORKOUT: "-- Оберіть збережене тренування --",
    SUBMIT_BUTTON: "Додати",
  },
  DASHBOARD_SKELETON: {
    FOOD_JOURNAL: "Журнал харчування",
    TRACK_PROGRESS: "Відстежуйте прийоми їжі, щоб стежити за своїм прогресом",
    TODAY_SUMMARY: "Підсумок за сьогодні",
    PROTEIN: capitalize(COMMON_TEXTS.PROTEIN),
    FAT: capitalize(COMMON_TEXTS.FAT),
    CARBOHYDRATE: capitalize(COMMON_TEXTS.CARBOHYDRATE),
    SUGAR: capitalize(COMMON_TEXTS.SUGAR),
    ADD_FOOD: "Додати їжу",
    AI_ANALIZE: "ШІ Аналіз",
    MANUAL_ENTER: "Ручний запис",
    ABOUT_FOOD: "Опишіть вашу страву для аналізу...",
    SUBMIT_BUTTON: "Додати",
    SAVE_BUTTON: "Зберегти",
    PROGRESS_OF_WEIGHT: "Прогрес ваги",
    WEIGHT_PROGRESS: "Відстеження ваги",
    CURRENT_WEIGHT: "Поточна вага:",
    NOT_AVAILABLE: COMMON_TEXTS.NOT_AVAILABLE,
    ENTER_TODAY_WEIGHT: "Записати сьогоднішню вагу",
    WEIGHT: capitalize(COMMON_TEXTS.WEIGHT),
    UNIT_KG: COMMON_TEXTS.UNIT_KG,
    WATER_TRACKER: "Відстеження води",
    GOAL: "Ціль: 0 000",
    UNIT_ML: COMMON_TEXTS.UNIT_ML,
    QUICK_ADD: "Швидке додавання:",
    ACTIVITY_PROGRESS: "Відстеження активності",
    MY_ENTER: "Мій запис",
    PLACEHOLDER: "Легкі садові роботи протягом 60 хвилин.",
  },
  FOOD_ENTRY_CARD: {
    BRACKFAST: capitalize(COMMON_TEXTS.BREAKFAST),
    LUNCH: capitalize(COMMON_TEXTS.LUNCH),
    DINNER: capitalize(COMMON_TEXTS.DINNER),
    SNACK: capitalize(COMMON_TEXTS.SNACK),
    DELETE_LOADING: "Видалення запису...",
    DELETE_SUCCESS: "Запис успішно видалено!",
    DELETE_ERROR: "Помилка:",
    DELETE_QUESTION: "Ви впевнені, що хочете видалити цей запис?",
    CONFIRM_DELETE: COMMON_TEXTS.CONFIRM_DELETE,
    CANCEL: COMMON_TEXTS.CANCEL,
    UNIT_KILOCALORIE: COMMON_TEXTS.UNIT_KILOCALORIE,
    UNIT_GRAM: COMMON_TEXTS.UNIT_GRAM,
    PROTEIN: COMMON_TEXTS.PROTEIN,
    CARBOHYDRATE: COMMON_TEXTS.CARBOHYDRATE.slice(0, 4),
    FAT: COMMON_TEXTS.FAT,
    SUGAR: COMMON_TEXTS.SUGAR,
  },
  MEAL_CARD: {
    ERROR: "Помилка:",
    RECIPE_ERROR: "ПОМИЛКА: Не вдалося знайти рецепт з ID:",
    SUBMIT_SUCCESS: "Запис успішно додано!",
    PORCE_QUANTITY: "Кількість порцій",
    WEIGHT: capitalize(COMMON_TEXTS.WEIGHT),
    UNIT_GRAM: COMMON_TEXTS.UNIT_GRAM,
    ADD_MEAL: "Додати прийом їжі",
    ANALIZE_AI: "ШІ Аналіз",
    MANUAL_ENTER: "Ручний запис",
    SEARCH_IN_DB: "Пошук у базі даних...",
    SEACRH: "Пошук...",
    CALORIES: capitalize(COMMON_TEXTS.CALORIES),
    CALORIES_SHORT: capitalize(COMMON_TEXTS.CALORIES).slice(0, 1),
    PROTEIN: capitalize(COMMON_TEXTS.PROTEIN),
    PROTEIN_SHORT: capitalize(COMMON_TEXTS.PROTEIN).slice(0, 1),
    CARBOHYDRATE: capitalize(COMMON_TEXTS.CARBOHYDRATE),
    CARBOHYDRATE_SHORT: capitalize(COMMON_TEXTS.CARBOHYDRATE).slice(0, 1),
    FAT: capitalize(COMMON_TEXTS.FAT),
    FAT_SHORT: capitalize(COMMON_TEXTS.FAT).slice(0, 1),
    SUGAR: capitalize(COMMON_TEXTS.SUGAR),
    SUGAR_SHORT: capitalize(COMMON_TEXTS.SUGAR).slice(0, 1),
    ADD_MY_RECIPE: "-- Або обрати мій рецепт: --",
    MY_RECIPE: "Мої рецепти:",
    G_100: "На 100г",
    SERVING: "На порцію",
    AI_PLACEHOLDER: "Опишіть вашу страву для аналізу...",
    MANUAL_PLACEHOLDER: "Введіть назву страви...",
    SELECT: "Обрано:",
    OPTIONS: "-- Оберіть прийом їжі --",
    SUBMIT_BUTTON: COMMON_TEXTS.SUBMIT_BUTTON,
  },
  NUTRION_DASHBOARD: {
    FOOD_JOURNAL: "Журнал харчування",
    TRACK_PROGRESS: "Відстежуйте прийоми їжі, щоб стежити за своїм прогресом",
    TODAY_SUMMARY: "Підсумок за сьогодні",
    TODAY_JOURNAL: "Сьогоднішній журнал",
    UNIT_GRAM: COMMON_TEXTS.UNIT_GRAM,
    PROTEIN: capitalize(COMMON_TEXTS.PROTEIN),
    FAT: capitalize(COMMON_TEXTS.FAT),
    CARBOHYDRATE: capitalize(COMMON_TEXTS.CARBOHYDRATE),
    SUGAR: capitalize(COMMON_TEXTS.SUGAR),
    BRACKFAST: capitalize(COMMON_TEXTS.BREAKFAST),
    LUNCH: capitalize(COMMON_TEXTS.LUNCH),
    DINNER: capitalize(COMMON_TEXTS.DINNER),
    SNACK: capitalize(COMMON_TEXTS.SNACK),
  },
  SUMMARY_CARD: {
    TOAST_SUCCESS: "Вага успішно додана!",
    TOAST_ERROR: "Будь ласка, введіть коректну вагу.",
    WEIGHT: capitalize(COMMON_TEXTS.WEIGHT),
    UNIT_KG: COMMON_TEXTS.UNIT_KG,
    NOT_AVAILABLE: COMMON_TEXTS.NOT_AVAILABLE,
    TITLE: "Прогрес ваги",
    WEIGHT_PROGRESS: "Відстеження ваги",
    CURRENT_WEIGHT: "Поточна вага:",
    ENTER_TODAY_WEIGHT: "Записати сьогоднішню вагу",
    SAVE_BUTTON: COMMON_TEXTS.SAVE_BUTTON,
  },
  WATER_TRACKER_CARD: {
    TOAST_ERROR: "Кількість води не може бути від'ємною.",
    TITLE: "Відстеження води",
    GOAL: "Ціль:",
    UNIT_ML: COMMON_TEXTS.UNIT_ML,
    QUICK_ADD: "Швидке додавання:",
    SUBMIT_BUTTON: COMMON_TEXTS.SUBMIT_BUTTON,
  },
};
