export const ACTIONS_TEXTS = {
  AI_ERROR: "Помилка аналізу ШІ: ",
  SERVER_ERROR: "Сталася невідома помилка. Перезавантажте сторінку.",
  DESCRIPTION_EMPTY: "Не може бути порожнім",
  ERROR_DB_SAVE: "Помилка бази даних: ",
  ADDED_SUCCESS: "Запис успішно додано!",
  CHECK_PREMIUM_ERROR: "Не вдалося провести запит. Ваша підписка вичерпана.",
  DELETE_SUCCESS: "Запис видалено!",
  CONNOT_CHECK_PREMIUM: "Не вдалося перевірити статус преміуму.",
  UNCORRECT_DATA: "Некоректні дані",
  CANNOT_SAVE: "Не вдалося зберегти: ",
  PROFILE_REFRESH: "Профіль успішно оновлено!",
  ACTIVITY: {
    NOT_AN_ACTIVITY:
      "Це не схоже на фізичну активність. Спробуйте описати її інакше.",
    SAVE_ERROR: "Помилка збереження активності:",
    SAVE_SUCCESS: "Активність успішно збережено!",
    ACTIVITY_ANALIZE_ERROR: "Помилка аналізу активності",
    EQUIPMENT_ERROR: "Будь ласка, вкажіть наявний інвентар та тривалість.",
    USER_PROFILE_ERROR: "Помилка отримання профілю користувача.",
    AI_NOT_RETURNED:
      "ШІ не повернув жодного плану тренувань. Спробуйте ще раз.",
    DB_SAVE: "План тренувань успішно згенеровано та збережено!",
    TRAINING_ERROR: "Помилка отримання тренування з плану.",
    TRAINING_SUCCESS: "Тренування успішно додано!",
    WORK_OUT_NAME_EMPTY: "Назва та опис тренування не можуть бути порожніми.",
    TRAINING_FAILED: "Не вдалося отримати тренування. Спробуйте ще раз.",
    TRAINING_START: "Тренування",
    TRAINING_END: "успішно завершено!",
    DB_ERROR: "Помилка БД: ",
  },
  FOOD: {
    NO_INGREDIENTS: "Не вдалося знайти інгредієнти у вашому запиті.",
    NUTRITION_ERROR: "Помилка API CalorieNinjas: ",
    NO_CORRECT_DATA: "Некоректні дані, надіслані на сервер.",
    NOT_IN_MANUAL_MODE: "Неправильний режим для цього екшену",
    NOT_ADDED: "Не вдалося додати запис: ",
    ADDED_START: "Додано",
    ADDED_END: "мл води!",
    NO_PRODUCTS_FOUND: "Не вдалося знайти продукти. Спробуйте інший запит.",
  },
  PROFILE: {
    UPDATE_SUCCESS: "Харчові цілі успішно оновлено!",
    WEIGHT_POSITIVE: "Вага має бути позитивним числом.",
    WEIGHT_START: "Вагу",
    WEIGHT_END: "кг збережено!",
  },
  RECIPES: {
    UMPTY_INGREDIENTS: "Список інгредієнтів порожній або некоректний.",
    UMPTY_AI: "ШІ повернув порожню відповідь (null).",
    NORMALIZED_ERROR: "Не вдалося розпізнати інгредієнти у вашому запиті.",
    CN_ERROR_START: "Помилка CalorieNinjas з ",
    CN_ERROR_END: ", ігноруємо.",
    WEIGHT_ERROR: "Не вдалося визначити вагу інгредієнтів.",
    RECIPE_START: "Рецепт ",
    RECIPE_END: " успішно збережено!",
    NOT_FOUND_ID: "ID рецепта не вказано.",
    DELETED_ERROR: "Не вдалося видалити рецепт.",
    RECEPE_ADD_SUCCESS: "Рецепт успішно додано!",
  },
};
