export const COMMON_TEXTS = {
  NOMTRACK: "NomTrack",
  CALORIES: "калорії",
  DAY: "день",
  DAYS: "дні",
  PROTEIN: "білки",
  FAT: "жири",
  SUGAR: "цукор",
  WATER: "вода",
  CARBOHYDRATE: "вуглеводи",
  BREAKFAST: "сніданок",
  LUNCH: "обід",
  DINNER: "вечеря",
  SNACK: "перекус",
  MONTH: "місяць",
  UNIT_KG: "кг",
  UNIT_GRAM: "г",
  UNIT_CM: "см",
  UNIT_ML: "мл",
  UNIT_KILOCALORIE: "ккал",
  UNIT_HOURS: "год",
  UNIT_MINUTES: "хв",
  UNIT_SECONDS: "сек",
  NOT_AVAILABLE: "N/A",
  WEIGHT: "вага",
  DELETE: "видалити",
  DELETE_SUCCESS: "Активність видалено!",
  CONFIRM_DELETE: "Так, видалити",
  CANCEL: "скасувати",
  MONDAY: "Понеділок",
  TUESDAY: "Вівторок",
  WEDNESDAY: "Середа",
  THURSDAY: "Четвер",
  FRIDAY: "П'ятниця",
  SATURDAY: "Субота",
  SUNDAY: "Неділя",
  SUBMIT_BUTTON: "Додати",
  SAVE_BUTTON: "Зберегти",
};
